### ISSUE TITLE
Google Keep crashes when using the top menu on the widget

### ISSUE THREAD

**Issue by WildS0ft** [Maxr1998/MaxLock#101]
If you try and make a new note from the top menu on the [Google Keep](https://play.google.com/store/apps/details?id=com.google.android.keep) **widget** it crashes.

**Comment by Maxr1998** [comment]
Thanks for mentioning. It doesn't crash for me, but freeze after unlocking. I will look into it.

**Comment by Maxr1998** [comment]
Merged into #113.
