### ISSUE TITLE
Failed to resolve: com.github.Maxr1998:material-intro:20044f88e8

### ISSUE THREAD

**Issue by jatin-lakhani** [Maxr1998/MaxLock#106]
Hey,

I just checked your app , Its a really awesome.

I'm trying to import this code but unable to find this library.
com.github.Maxr1998:material-intro:20044f88e8

Could you help me to resolve this issue?

Thanks in advance.

**Comment by Maxr1998** [comment]
I hope the new library version doesn't clash with MaxLock. Please comment here if you can build successfully now.

**Comment by harirao001** [comment]
Hey,

I am having same issue.

I have tried with updated library. Some of the dimens and layout are still missing.

Here is my logcat  that are showing missing files:

Error:(25, 38) No resource found that matches the given name (at 'layout_marginBottom' with value '@dimen/mi_pager_margin_bottom').

/MaxLock-master/app/src/main/res/layout/fs_config_box.xml
Error:(54, 32) No resource found that matches the given name (at 'layout_height' with value '@dimen/mi_pager_margin_bottom').
/MaxLock-master/app/src/main/res/layout-land/fs_information.xml
Error:(43, 36) No resource found that matches the given name (at 'layout_height' with value '@dimen/mi_pager_margin_bottom').
/MaxLock-master/app/src/main/res/layout/fs_information_box.xml
Error:(32, 32) No resource found that matches the given name (at 'layout_height' with value '@dimen/mi_pager_margin_bottom'). 

Its my request you to provide solution on this ASAP.

Thank you.

**Comment by Maxr1998** [comment]
Gonna look at it very soon.
