### ISSUE TITLE
Could't launch Pica Comic if locked.

### ISSUE THREAD

**Issue by acsway878787** [Maxr1998/MaxLock#108]
[Pica Comic v2.0.3.13](http://www.picacomiccn.com/PicaComic_beta_test_2.0.3.13.apk)
Device: Sony Xperia TX
Android: 6.0.1
Xposed Framework: 87
MaxLock: 6.4.1

**Comment by Maxr1998** [comment]
Could you send me your logs, please? I installed it, but I didn't want to give any permissions to an app I don't understand, so I couldn't test and thus uninstalled it again.

**Comment by acsway878787** [comment]
After unlocked, it would stick at the initial frame.
 `W/System.err(2770): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
W/System.err(2770):at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
W/System.err(2770):at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
W/System.err(2770): at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
W/System.err(2770): at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:617)
W/System.err(2770): at com.picacomic.fregata.activities.LoginActivity$1.onFinish(LoginActivity.java:116)
W/System.err(2770): at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
W/System.err(2770): at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(2770): at android.os.Looper.loop(Looper.java:148)
W/System.err(2770): at android.app.ActivityThread.main(ActivityThread.java:5481)
W/System.err(2770): at java.lang.reflect.Method.invoke(Native Method)
W/System.err(2770): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
W/System.err(2770): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
W/System.err(2770): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
`

**Comment by Maxr1998** [comment]
Whelp, it seems that MaxLock would need to have a slight delay before pushing itself into foreground, or launch without pausing the locked activity.. That's a "bug" in the locked app itself, not sure if I can fix it in ML..

**Comment by Maxr1998** [comment]
Merged into #113.
