### ISSUE TITLE
Support Live Wallpapers in Lockscreen

### ISSUE THREAD

**Issue by piepie62** [Maxr1998/MaxLock#110]
This is a very minor thing, but I would like it if I could use the live backgrounds installed on my devices as the background here (aka have a separate wallpaper setting for MaxLock). I understand if this is too hard or not within your scope of interest, just a thought. :)

**Comment by Maxr1998** [comment]
This is sadly not really possible, at most I could allow to show the underlying system wallpaper, which could also be a live wallpaper..

**Comment by Maxr1998** [comment]
Fixed in 09a16259188276bf642dfcdddc7a448f10e6b882 and successive commits.
