### ISSUE TITLE
whitelist activities from other apps

### ISSUE THREAD

**Issue by My1** [Maxr1998/MaxLock#112]
dont ask me why but apparently the settings app can be called with activities from other apps, for example 6the mobile settings have an activity from the phone app on my Note 4:
https://www.dropbox.com/s/oav8251lvrt26zj/2017-06-09%2007.12.05.png?dl=0

and the settings app doesnt have that activity and the phone app isnt even listed.

**Comment by Maxr1998** [comment]
It's still the settings app, the Java package name is just the same as in the phone app - but we already discussed this on Telegram ;)
