### ISSUE TITLE
App crashes on nougat (but issue may not be related to nougat)

### ISSUE THREAD

**Issue by hacker1024** [Maxr1998/MaxLock#117]
When trying to launch the app:

`AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.Maxr1998.xposed.maxlock/de.Maxr1998.xposed.maxlock.ui.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.preference.TwoStatePreference.isChecked()' on a null object reference`

**Comment by Maxr1998** [comment]
@hacker1024 Did compile the release yourself? This is normally already fixed, at least it doesn't crash for me..

**Comment by hacker1024** [comment]
I downloaded from Google Play. I'll try compiling the master branch myself, thanks.

**Comment by Maxr1998** [comment]
@hacker1024 Then it's definitely already fixed. GP version is not supposed to be used on Nougat.

**Comment by hacker1024** [comment]
Oh, OK. Sorry.
