### ISSUE TITLE
Not working on 7.1 

### ISSUE THREAD

**Issue by taskifydps** [Maxr1998/MaxLock#123]
Crashing app

**Comment by Maxr1998** [comment]
Send me a logcat, your current report doesn't help me at all. Also, it cannot be crashing because of 7.1, as it works perfectly fine for me on that OS.

**Comment by Maxr1998** [comment]
@Holymsophy logcat of the crash?

**Comment by Maxr1998** [comment]
Please use the beta. The crashes were probably already fixed.
