### ISSUE TITLE
Weird KitKat and below bootloop because of RemotePreferences

### ISSUE THREAD

**Issue by acsway878787** [Maxr1998/MaxLock#127]
Phone: ASUS PadFone S
Android Version:4.4.2
Xposed version: 54

**Comment by Maxr1998** [comment]
@acsway878787 Known issues. Working on it already in the last few weeks.

**Comment by Maxr1998** [comment]
Nope, not yet. I just didn't get to identify the issue by now, and didn't want to push a potentially unstable version onto devices with KitKat, so every 7.X version is Android 5.0+. Hopefully I can fix this bug in the near future.

**Comment by Maxr1998** [comment]
I couldn't ever reproduce this bug sadly, neither on my devices with KitKat nor the Emulator. It seems to be a vendor specific bug in the framework representation. However, next MaxLock release will drop KitKat support, as it's only used on a very small percentage of devices.
Thus, I'll be marking this as wontfix and closing this issue..
