### ISSUE TITLE
Force close app when opened for the first time!!

### ISSUE THREAD

**Issue by drxgxn** [Maxr1998/MaxLock#128]
Hi Maxr1998! 

First of all thank you for making such a useful app. I also appreciate you responding regularly on your xda post comments.

Here's the problem. I updated my One Plus 3 to Resurrection Remix Oreo and installed the maxlock activated and rebooted the phone but as soon as i open it, the screen stops for few seconds and then it force closes without even showing the UI. I am atttaching the LOGCAT.txt file along with the screenshot of error. I started having this issue with nougat as well...thats why i updated to oreo in the first place.

Device Specifications
One Plus 3
Resurrection Remix Oreo v6.0.0-20180220-oneplus3-official
Android version 8.1.0
![screenshot_holo_launcher_20180226-234216](https://user-images.githubusercontent.com/26479749/36688980-ff3a9f60-1b25-11e8-9e3e-6a2a3674cdf6.png)
![screenshot_settings_20180227-002009](https://user-images.githubusercontent.com/26479749/36689004-0d18a15e-1b26-11e8-87ad-0b52615667ab.png)
[2018-02-26-23-45-29.txt](https://github.com/Maxr1998/MaxLock/files/1759881/2018-02-26-23-45-29.txt)

**Comment by Maxr1998** [comment]
Yep, known issue and actually already fixed in git. I will hopefully push an update soon.
