### ISSUE TITLE
MaxLock implementation preference not available

### ISSUE THREAD

**Issue by Melab** [Maxr1998/MaxLock#129]
I'm running MaxLock on Android 4.4.2 (Acer Iconia A1) and on Android 4.4.4 (Motorola Droid MAXX). I am not rooted on either device. I have found out that there is a setting called "MaxLock implementation" that can be used to select a mode that doesn"'t require root/Xposed, but I do not see it on the app's screen. Where is it?

**Comment by Maxr1998** [comment]
@Melab Well, read the changelog another time 😉
The no-Xposed mode only works on Nougat and above.
