### ISSUE TITLE
Issue with Homebutton and MaxLock 7.0

### ISSUE THREAD

**Issue by zoff99** [Maxr1998/MaxLock#130]
android 7.1
Maxlock 7
my device has a physical home button, which is also the fingerprint reader.

after unlocking an app with Maxlock (via fringerprint) sometimes "home button press" is sent also and i end up on the home screen instead of the app.

Maxlock 6.x does not do this

**Comment by Maxr1998** [comment]
This sounds more like your home button is acting up - MaxLock doesn't interfere with it in any way, and only uses the plain Android Fingerprint API, regardless where the scanner is located.

**Comment by zoff99** [comment]
why did you close this? it works perfectly with an earlier version of Maxlock.
the home button also works fine in all other situations (the phone is brand new)

**Comment by Maxr1998** [comment]
Well, as I stated: MaxLock has nothing to do with this, so I can't say why it only appears with the new version.

**Comment by Maxr1998** [comment]
Take a look at the commit history, I didn't even change anything in Fingerprint handling execpt for some UI changes since the last release:
https://github.com/Maxr1998/MaxLock/commits/master/app/src/main/java/de/Maxr1998/xposed/maxlock/ui/lockscreen/FingerprintView.java
