### ISSUE TITLE
Redesign app

### ISSUE THREAD

**Issue by jahirfiquitiva** [Maxr1998/MaxLock#134]
Hello

I would like to ask you to redesign the app as the current design seems a bit outdated and it would make the app more pleasant to use

Basically, something like [this app](https://play.google.com/store/apps/details?id=com.getkeepsafe.applock) which extracts colors from the app icons and stuff

It looks really well

I hope you consider it and maybe even make it happen

Thanks in advance

**Comment by Maxr1998** [comment]
I don't think my app looks outdated in any way, it's just different. I'll probably tweak the lockscreen a little in the future, but I don't really see a problem right now..
Color extraction for the color wallpaper looks like a nice feature, maybe I'll add it if it's not too much work.
