### ISSUE TITLE
Randomly activates lock

### ISSUE THREAD

**Issue by jaqxues** [Maxr1998/MaxLock#135]
Sometimes MaxLock just randomly locks my apps. I open the "recent Tabs" Screen, reopen the app and it is unlocked. Also, everytime i open the "recent Tabs", an error occurs: Field not found. It causes weird behaviour (wallpaper is now the "recent Tabs" thumbnail)

Android 5.1
Error Log: https://pastebin.com/dtQHk7j2

**Comment by Maxr1998** [comment]
Quickly checking recents doesn't cause the app to relock, that's intended behavior. If you switch to another app in between, you do have to enter your password again.

Thanks for the logs on the recents thumbnails, that's a bug I seem to have missed on Android LP.
