### ISSUE TITLE
Task thumbnail hiding broken on Marshmallow

### ISSUE THREAD

**Issue by malitech** [Maxr1998/MaxLock#136]
Hello,
Maxlock has started crashing too much and spamming xposed log and draining battery life. Here's the log attached. I have disabled it at the moment.
[error.log](https://github.com/Maxr1998/MaxLock/files/1969308/error.log)

Please fix this. Thanks for the nice app.

**Comment by Maxr1998** [comment]
Does the app itself crash? I'd need a logcat for that as well. The Xposed errors are from the hide recents thumbnail component, you can just disable that in MaxLock settings for now. Which Android version do you use? Which app version? Maybe just send me the report.zip via email through the send feedback item in the app..

**Comment by malitech** [comment]
The app has never crashed itself, only the xposed log is being spammed extremely. Oh yes, I noticed but I haven't enabled that. I have another app called "Recents Tuner" that I'd been using since a long time. So, I never enabled it in maxlock because maxlock doesn't support transparent thumbnails in the recent screen, only coloured thumbnails.

Nexus 5, stock marshmallow. I had 7.0.2. The error persists in 7.0.3 too.

I'll send the report shortly.

**Comment by Maxr1998** [comment]
Could you try the attached build?
[ML-7.0.3-release.zip](https://github.com/Maxr1998/MaxLock/files/2026376/ML-7.0.3-release.zip)
Rename to .apk before installing.

**Comment by malitech** [comment]
Hey! Thanks for this. It seems to be fixed. I will let you know if the errors come up again.
What was the issue? Why was it crashing? May I know?

**Comment by Maxr1998** [comment]
Actually, nothing too special. As you could read in the logs, I was accessing a mTask field which doesn't exist before Marshmallow (dumb oversight on my end). Now, I switched to the task Object from the method parameters, which exists in all versions of my hooked method.

**Comment by malitech** [comment]
Oh I see. Thanks a lot buddy!
