### ISSUE TITLE
Activity without layout should not be blocked 

### ISSUE THREAD

**Issue by intika** [Maxr1998/MaxLock#14]
Hi :) 

First as always thanks for your amazing work. 

when we protect an app if an activity without layout is running, it should not ask for the password

example : 
protecting gravitybox 
create a shortcut with gravitybox to do an automated action with tasker or llama etc...

It could be a nice feature for futur version to allow hidden activity without password for certain app.

its may be not a bug

Thanks

**Comment by intika** [comment]
System : Kitkat 4.4.4 - Used simple protection with patern

**Comment by Maxr1998** [comment]
I will probably add an per-activity lock in next version, that you can disable certain activities. Thanks for reporting.

**Comment by intika** [comment]
Thanks a lot :) 
if i have some free time i will post a pull request

**Comment by Maxr1998** [comment]
Ok, I created the ability to exclude activities from lock, but I haven't tested it yet and still have a small bug to fix. Stay tuned!

**Comment by intika** [comment]
Thanks :) it's cool
i have done a lot of change on my version i am adding a pull request
