### ISSUE TITLE
Wire needs to be unlocked 2 times!

### ISSUE THREAD

**Issue by kernoeb** [Maxr1998/MaxLock#141]
Hi, I have an **issue** with **Wire** app.
I start the app, the loading screen appears, and then I can **unlock**. 
But when I unlock, I come back to my launcher, then I have to click again on **Wire**, unlock the app, and finally it's okay.

**Watch the video:**
[youtu.be/uvJLgdCzOvw](https://youtu.be/uvJLgdCzOvw)

However, I **can't give you a logcat**... _(logcat read failure with ADB)_

**My phone:**
Moto E LTE (2nd gen)
XT1524
lineage_surnia 7.1.2

kernoeb

**Comment by Maxr1998** [comment]
You're using the Xposed implementation, right?

**Comment by kernoeb** [comment]
> You're using the Xposed implementation, right?

Yep
![maxlock2](https://user-images.githubusercontent.com/24623168/44900563-2b6ff780-ad05-11e8-8d2f-82035874dafa.png)

**Comment by Maxr1998** [comment]
Also a duplicate of #113 - please read there for further updates.
