### ISSUE TITLE
apk and project bulding errors

### ISSUE THREAD

**Issue by BhavikMangukiya** [Maxr1998/MaxLock#147]
hey developer's

i am experiencing apk and project building errors i have tried android studio eclipse and idea ide
with windows and ubuntu

but no use please see if there is an error exist or it is with my instance

and also suggest ide or platform to open and make use of this project

**Comment by Maxr1998** [comment]
No offense, but without any info/details, I can't really help you (at all). MaxLock should build just fine inside Android Studio, or through `gradle assembleRelease`. However, I can't recommend to use the current master branch, as it's incomplete and unstable. Oh, and please don't use Eclipse in 2019, it's unsupported for a long time now.
