### ISSUE TITLE
Protecting Package installer is not working

### ISSUE THREAD

**Issue by intika** [Maxr1998/MaxLock#15]
Hi again :) 

Protecting package installer is not working 

let say if we want to uninstall an app, the code is requested, then afterward the uninstall windows dissapear/not displayed. 

Thanks 

System : Kitkat 4.4.4 - Used simple protection with patern

**Comment by intika** [comment]
Solved
Was caused by xposed module "prevent running"
Thanks

**Comment by Maxr1998** [comment]
There's still an error in Package Installer, but you meant something else, ok.

**Comment by intika** [comment]
thanks for the answer "prevent running" was killing maxlock resulting in that problem
