### ISSUE TITLE
UI won't load after system restart

### ISSUE THREAD

**Issue by matej-vrba** [Maxr1998/MaxLock#156]
After enabling edxposed module and restarting screen is black, I can access power menu, but it looks different than usual(no skin)
EdXposed version: 0.5.5.2_4683
EdXposed manager version: 4.6.2(46200)
Andoid: 11 (Red Velvet Cake, API30)
Device: Xiaomi Redmi Note 7 with PixelExperience ROM
SOC: AArch64 Processor rev 2 (aarch64) arm64-v8a(arm64)
SELinux status: Permissive
Verified Boot is deactivated
log: https://termbin.com/w529

I'm not sure if it's EdXposed or MaxLock issue, but since other modules work, I'm reporting it here.

**Comment by saitarunsareddy** [comment]
Hi @Mearsu is this issue fixed for you??

**Comment by matej-vrba** [comment]
No, but I still have the same version 7.0.6
