### ISSUE TITLE
Option to take a picture of "thief" if authentication fails

### ISSUE THREAD

**Issue by Maxr1998** [Maxr1998/MaxLock#29]
When the password that was entered is wrong, take a picture with the devices front-camera

**Comment by Magissia** [comment]
If #100 is taken care of, it would be easily feasible with more customization that you may offer by yourself

**Comment by Maxr1998** [comment]
Yes, I think this is better than adding additional specific code and a new permission for a feature that may seem bloated to many. And on top of that, you can do a lot more wuth Tasker, e.g. sending messages or even erasing the locked app's data after too many failed attemps.
I will probably add a Tasker guide to my website then.

**Comment by Maxr1998** [comment]
Tasker support added as of  593a7012, closing.
