### ISSUE TITLE
Turning the setting "Go directly to Fake Die" doesn't really do anything.

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [Maxr1998/MaxLock#37]
In MaxLock settings, turning on the settings concerning going directly to Fake Die rather than having to input a report phrase doesn't work.

Phone: Nexus 5
Android: 4.4.4

**Comment by Maxr1998** [comment]
Yeah, already got reported on XDA. Easy fix, already know why..

**Comment by Maxr1998** [comment]
Fixed with 214b94152ec6a0245687d41b391ae93219c7f708.
