### ISSUE TITLE
"Hide App from App Drawer" takes app into oblivion. Where is it? lol

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [Maxr1998/MaxLock#38]
I thought I was done with the app settings, which I am, so I hid it. Now I wanted to get the app version for these bug reports and feature requests and couldn't figure out how to get it to come out from the darkness.

Phone: Nexus 5
Android: 4.4.4

**Comment by Maxr1998** [comment]
Open Xposed Installer, click in modules, select MaxLock. Easy!
