### ISSUE TITLE
Launch default browser for MaxLock Website when the device is pre-KitKat

### ISSUE THREAD

**Issue by TechnoSparks** [Maxr1998/MaxLock#44]
The current version of MaxLock will open the MaxLock website right within the app itself with the help of `webview`.
However due to the obviously old version of the `webview`, devices with Android version prior to KitKat will face compatibility problems. `webview` of the old Android versions was built for the web features at the time, since web technologies matures overtime and new features are introduced, versions that are stuck in time won't able to process and display the new things properly.

To overcome this limitation, I suggest for the MaxLock app to summon a browser to access the MaxLock website **if** the user is using Android prior to KitKat.

Lollipop and newer versions won't suffer from this problem, as `webview` itself is now a separate module, updatable from the Play Store. In the future, KitKat's `webview` will also fall into the same demise.

**Comment by Maxr1998** [comment]
This seems like a good idea, especially all the problems we could have in the website when accessing from an old webview..

I'll change this now.

In the future, I plan to ditch the WebView completely and use Chrome custom tabs (as long as it's backwards compatible, but it should, we just need to wait until it's released..)

**Comment by Maxr1998** [comment]
Fixed with 3c75b616218103690ac825b85d9763f2e225cae4
