### ISSUE TITLE
Kik and Viber locking issues

### ISSUE THREAD

**Issue by ghost** [Maxr1998/MaxLock#62]
I tried locking kik messenger. but it opens fine, without even needing a password. Leave the kik UI running in the foreground, lock the screen and unlock, it asks password for kik. Otherwise, it doesn't even ask. 

And with Viber. It asks password 3 times. Don't know why.

**Comment by Maxr1998** [comment]
Thanks, I will take a look at it.

**Comment by VitaminX4** [comment]
Thanks for the reply. And thanks for this awesome app.

**Comment by djforesm** [comment]
I would also like to add ES File Explorer, Bank of America, keep, and wickr to the list of currently not locking apps when set to lock

**Comment by djforesm** [comment]
Scratch that, just needed to restart

**Comment by Maxr1998** [comment]
Merged into #113.
