### ISSUE TITLE
Please allow lock app not showing in launcher(like installer).

### ISSUE THREAD

**Issue by fanthos** [Maxr1998/MaxLock#79]

**Comment by Maxr1998** [comment]
MaxLock already has this option, if you mean hide MaxLock from launcher.

**Comment by WildS0ft** [comment]
A wild guess would be that he perhaps means the notification you get to lock a newly installed app. "_Lock newly installed app?_"

@fanthos If that's the case, you already have the option to "_Never show again_" or "_Lock App_". Not sure how to reset the choice though if one would to choose not to show it again.

**Comment by Maxr1998** [comment]
@WildS0ft Hm, might be possible.. Let's wait for an answer from @fanthos :P
BTW, I will soon add an extra toggle to disable and enable the "New app" notification.

**Comment by fanthos** [comment]
I was tried to lock com.android.packageinstaller in an earlier version.  There seems a bug that app installer not listed in Android 6.0.  It works good in recent version of MaxLock.
