### ISSUE TITLE
ProtonMail app will not launch properly when locked

### ISSUE THREAD

**Issue by WildS0ft** [Maxr1998/MaxLock#87]
The [ProtonMail App](https://play.google.com/store/apps/details?id=ch.protonmail.android) (1.2.4) won't get passed the initial splash screen when locked, regardless of previous login status.

**Device:** Sony Z1 Compact (D5503)
**Android:** 5.1.1
**Xposed Framework:** 81
**MaxLock:** 6.2.1

**Comment by Maxr1998** [comment]
Investigating, please wait for further responses.

**Comment by Maxr1998** [comment]
I see. I may add that as a default option.

**Comment by Maxr1998** [comment]
Merged into #113.
