### ISSUE TITLE
White background, white dots

### ISSUE THREAD

**Issue by WildS0ft** [Maxr1998/MaxLock#89]
**Bug 1:** When launching MaxLock it sometimes fails to fetch the wallpaper and instead shows a white background. This happens very rarely (on multiple devices) and all you have to do is clear it from the "recent apps" menu and run it again.

**Bug 2:** If you are using a "live background" and not previously used a static one when launching MaxLock, it will also show a white background. This can't be "fixed" with restarting the app. You'll have to set a static wallpaper and launch MaxLock, making sure the app fetches the image in both portrait and landscape mode (tablet). You are then able to switch back to the live background. MaxLock will now use the previously retrieved static images instead of a white background.

**Suggestion:** If MaxLock fails to retrieve the wallpaper or the device is using a "live background" on first run, use another colour besides white for the background or the dots. If both the dots and the background are white it makes it very difficult to enter the correct pattern.

**Comment by Maxr1998** [comment]
Possibly fixed in new version, at least bug 1. Investigating on bug 2.
Normally, MaxLock already should display a orange background when it can't load the system wallpaper..

**Comment by WildS0ft** [comment]
Strange. My _Background image_ is set to _Wallpaper_ and _Custom color_ is set to orange as default (I have never changed it).

I noticed the second bug on my tablet, since I have a static image on my phone.
**Device:** Sony Z2 Tablet (SGP511)
**Android:** 5.1.1
**Xposed Framework:** 81
**MaxLock version:** 6.2.1

I will set a live background on my phone and reset MaxLocks settings to see if it also happens on it. Stand by...

**Comment by WildS0ft** [comment]
I set a live background, deleted MaxLock's app data and rebooted the phone. But MaxLock still has my previous wallpaper stored so that's shown. Where's MaxLock's background stored? So I can delete it and test again...

**Comment by Maxr1998** [comment]
I think Android itself stores the previous wallpaper when you have set a live wallpaper.. And if there wasn't a previous wallpaper, it uses the default system one. BTW, Android stores the wallpaper at /data/system/users/<id>/wallpaper.

**Comment by Maxr1998** [comment]
@Maxr1998 I deleted the file, and it now uses the default wallpaper. I believe the issue is somewhere else..
I'll watch this issue closely, please report back after I pushed the next update.

**Comment by WildS0ft** [comment]
My wallpaper was actually stored in _data/system/users/0_ simply as _wallpaper_ :P

Success! I reproduced the bug.

**This is exactly what I did:**
1. Set a live background (Light flow)
2. Renamed _wallpaper_ in _data/system/users/0_ simply as _wallpaper_ to _wallpaper.bak_
3. Rebooted phone
4. Deleted MaxLock app data
5. Launched MaxLock and followed the first run guide and marked all the checkboxes (allowed ML in device administrators)
6. Set MaxLock protection to _Pattern_
7. Turned ON _Quick unlock_ under _Password and PIN_
8. Closed MaxLock and removed it from _recent apps_
9. Started MaxLock again - White image...

**Comment by WildS0ft** [comment]
> Possibly fixed in new version, at least bug 1.

The following might be redundant information to you, but I'd rather be thorough.

**Bug 1** keeps happening more often today for some unknown reason and often requires the app to be killed several times before the background is shown.

Every locked app has a black background, except for MaxLock, which either has a white background or my wallpaper (after several attempts). If I log in to ML when I see the wallpaper and then minimize the app, all the other locked apps gets the wallpaper as well. Doesn't work if I manage to log in to ML when I have the white background there. If I turn off my screen (locks the phone) it's back to black for apps, even though ML still isn't locked and can just be maximized from the recent apps menu.

> please report back after I pushed the next update.

I will =)

**Comment by Maxr1998** [comment]
Really weird. I actually cache the Wallpaper via a SoftReference, means it can be dropped when the device requires RAM. Seems your device drops it more often and then doesn't reload it, without triggering the error handling. The black and white backgrounds are just the default theme's window_backgrounds.

**Comment by WildS0ft** [comment]
Deleted _Cache_ and _Dalvik Cache_ in TWRP (just to test). 685 MB RAM free, nothing changed.

My tablet just uses the previous background I had before changing to a live one (data/system/users/0/wallpaper).

**Comment by WildS0ft** [comment]
After some more rigorous testing I found what's causing the problem. My custom wallpaper is the culprit, but only on the phone, not on the tablet. The following tests are therefore made on my phone.

**ML 6.2.1:**
**Live background** and no _wallpaper_ (which isn't created until you set a static one) gives you a **white** background in ML and a **dark grey** in other locked apps.
**Default static wallpaper** presents no issues. But it sometimes takes a split second to load the background (you can see the white background in ML and the dark grey one in locked apps).
**Custom static wallpaper** only works a very few times when launching ML but for the most part it acts like the same as not having a _wallpaper_ file at all. If you however see the wallpaper and minimize ML (regardless of unlocking it or not) then the wallpaper is shown in other closed apps until you kill ML from recent apps.

**ML 6.2.0:**
**Live background** and no _wallpaper_ gives you a **black** background in both ML and every other locked app.
**Default static wallpaper** same as 6.2.1 except ML and other locked apps has a **black** background.
**Custom static wallpaper** same as 6.2.1 except ML and other locked apps has a **black** background.

**ML 6.1.1:**
**Live background** and no _wallpaper_ gives you a **black** background in both ML and every other locked app.
**Default static wallpaper** presents no issues.
**Custom static wallpaper** presents no issues.

wallpaper_info.xml when using a static wallpaper (doesn't differ between default or custom)
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<wp width="1440" height="1280" name="" />

```
wallpaper_info.xml when using the live background _Phase Beam_ (comes with the phone)
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<wp width="1440" height="1280" name="" component="com.android.phasebeam/.PhaseBeamWallpaper" />

```

When selecting the custom background (1920 x 1080) I have to crop the image with Sony's Album crop tool. I select the whole image and click on save. I noticed that the _wallpaper_ file created is 2276 x 1280 whilst the Sony one is only 1440 x 1280, it's also slightly smaller in file size (409 kB vs 699 kB). The wallpaper_info.xml doesn't change either even though the image size differs.

Not sure how much of this is to any help.

**Comment by WildS0ft** [comment]
MaxLock version 6.3

**Live background** and no _wallpaper_ now gives you a black background in ML and apps.
**Default static wallpaper** presents no issues.
**Custom static wallpaper** no longer presents any issues either.
