### ISSUE TITLE
MaxLock doesn't prompt for password if the app is minimized

### ISSUE THREAD

**Issue by WildS0ft** [Maxr1998/MaxLock#90]
The MaxLock app itself doesn't prompt you to re-enter any login credentials if the app gets minimized (home button).

**Comment by Maxr1998** [comment]
Working as intended. MaxLock doesn't get locked by the default hooks, but by extra code in Settings activity. I believe it shouldn't ask for unlock until you closed your setup session.

**Comment by WildS0ft** [comment]
Thanks, then I know =) Wasn't really an issue for me, reported it anyway since I thought it was an unintended bug I found.
