### ISSUE TITLE
Xposed Installer locking issues

### ISSUE THREAD

**Issue by WildS0ft** [Maxr1998/MaxLock#91]
This one is a bit hard to explain without a lot of text. But here goes... When using MaxLock on my **tablet** and having both the _Xposed Installer_ app and _Settings_ locked, I get password prompt loops when I try to install any module via the Xposed Installer. This **does not happen on my phone** and the outcome seems to be somewhat random.

**Devices:** Sony Z2 Tablet (SGP511) **&** Sony Z1 Compact (D5503)
**Android:** 5.1.1
**Xposed Framework:** 81
**MaxLock version:** 6.2.1
**Locking type:** Pattern

**Case 1:**

> 1. Launches Xposed Installer app **enters code for Xposed Installer**
> 2. Navigates to the Xposed download menu and picks a mod
> 3. Swipes right and clicks on _Download_ **enters code for Package installer**
> 4. **enters code for Package installer**
> 5. **enters code for Package installer**
> 6. **enters code for Xposed Installer**
> 7. Is now back out to the Xposed download menu, no installation initialized
> 8. Clicks on _INSTALL_ (in Xposed) **enters code for Package installer**
> 9. **enters code for Xposed Installer**
> 10. Is now back out to Xposed download menu, no installation initialized
>     _Now just loops steps 8-10._

**Case 2:**

> 1. Launches Xposed Installer app **enters code for Xposed Installer**
> 2. Navigates to the Xposed download menu and picks a mod
> 3. Swipes right and clicks on _Download_ **enters code for Package installer**
> 4. Another **Package installer prompt**, but this time presses the **back button**
> 5. **enters code for Xposed Installer**
> 6. Is now back out to Xposed download menu, no installation initialized

**Case 3:**

> 1. Launches Xposed Installer app **enters code for Xposed Installer**
> 2. Navigates to the Xposed download menu and picks a mod
> 3. Swipes right and clicks on _Download_ **enters code for Package installer**
> 4. **enters code for Xposed Installer**
> 5. Is now back out to Xposed download menu, no installation initialized

**Case 4:**

> 1. Launches Xposed Installer app **enters code for Xposed Installer**
> 2. Navigates to the Xposed download menu and picks a mod
> 3. Swipes right and clicks on _Download_ **enters code for Package installer**
> 4. **enters code for Package installer**
> 5. **enters code for Package installer**
> 6. Is shown the Android installation prompt with app permissions (Cancel - Install)
> 7. Clicks on Install (not in Xposed)
> 8. **enters code for Package installer** (mod getting installed in the background)
> 9. **enters code for Xposed Installer**
> 10. Is shown Xposed Download menu, no prompt for a (un)successful installation of mod

**Case 5:** (mod already downloaded)

> 1. Launches Xposed Installer app **enters code for Xposed Installer**
> 2. Navigates to the Xposed download menu and picks the previously downloaded mod
> 3. Clicks on _INSTALL_ **enters code for Package installer**
> 4. **enters code for Package installer**
> 5. Is shown the Android installation prompt with app permissions (Cancel - Install)
> 6. Clicks on Install
> 7. **enters code for Package installer**
> 8. **enters code for Package installer**
> 9. **enters code for Package installer**
> 10. **enters code for Xposed Installer**
> 11. Is now back out to Xposed download menu, the mod got installed but yet again doesn't show the default "app (un)successfully installed" window.

And so on... Any ideas?

**Comment by WildS0ft** [comment]
**MaxLock version 6.3**

Trying to install an app through the Xposed installer is still not possible when **package installer** and **Xposed installer** are both locked.

**Case:** Downloads an app and when it's finished it prompts for the "Packet installer" then immediately after you get the Xposed installer password prompt, it then just shows the download screen with nothing happening. If you click on install again it just does the same all over again.

Using a grace period in ML makes the installation possible through the Xposed installer app.

**Comment by Maxr1998** [comment]
Merged into #113.
